apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - bundles.yaml

helmGlobals:
  chartHome: charts/trust-manager-v0.24.0

helmCharts:
  - name: trust-manager
    version: v0.24.0
    releaseName: trust-manager
    namespace: cert-manager
    valuesFile: values.yaml
