apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: woodpecker
helmCharts:
  - name: woodpecker
    repo: https://woodpecker-ci.org/
    releaseName: woodpecker
    namespace: woodpecker
    valuesFile: values.yaml
