apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: woodpecker
resources:
  - server-pdb.yaml
  - agent-pdb.yaml
helmCharts:
  - name: woodpecker
    version: 3.6.5
    repo: https://woodpecker-ci.org/
    releaseName: woodpecker
    namespace: woodpecker
    valuesFile: values.yaml
