apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-platform-images
spec:
  background: false
  webhookConfiguration:
    failurePolicy: Fail
    timeoutSeconds: 30
  rules:
    - name: verify-platform-image-signatures
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "<REGISTRY>/<PROJECT>/*"
          failureAction: Audit
          mutateDigest: true
          verifyDigest: true
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: k8s://<NAMESPACE>/<COSIGN_PUBLIC_KEY_SECRET>
                    rekor:
                      url: https://rekor.sigstore.dev
