apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: verify-signed-platform-images
spec:
  evaluation:
    admission:
      enabled: true
    background:
      enabled: true
  validationActions:
    - Audit
  failurePolicy: Fail
  webhookConfiguration:
    timeoutSeconds: 15
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
  matchImageReferences:
    - expression: "image.registry == '<REGISTRY>'"
  attestors:
    - name: approvedCosignKey
      cosign:
        key:
          data: |
            <COSIGN_PUBLIC_KEY>
        ctlog:
          url: "https://rekor.sigstore.dev"
          insecureIgnoreTlog: false
          insecureIgnoreSCT: false
  validationConfigurations:
    mutateDigest: true
    required: true
    verifyDigest: true
  validations:
    - expression: >-
        images.containers.map(image, verifyImageSignatures(image, [attestors.approvedCosignKey])).all(result, result > 0)
      message: Images from the selected registry must carry a valid Cosign signature.
