apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
components:
  - ../../components/network-isolation
  - ../../components/postgres-client
  - ../../components/external-web-egress
  - ../../components/external-smtp-egress
  - ../../components/external-database-egress
  - ../../components/kubernetes-api-egress
helmGlobals:
  chartHome: charts/kube-prometheus-stack-87.4.0
helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: monitoring
    includeCRDs: true
    valuesFile: values.yaml
