apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: platform-default-deny
  labels:
    app.kubernetes.io/part-of: platform-network-isolation
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
