apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
helmGlobals:
  chartHome: charts/traefik-41.2.0
helmCharts:
  - name: traefik
    releaseName: platform-traefik
    namespace: traefik
    valuesFile: values.yaml
