deployment:
  replicas: 3

podDisruptionBudget:
  enabled: true
  minAvailable: 2

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

service:
  enabled: true
  type: LoadBalancer

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    tls:
      enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus:
    enabled: true
    service:
      enabled: true
    serviceMonitor:
      enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi
