apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - namespace.yaml
helmCharts:
  - name: metallb
    version: 0.16.1
    repo: https://metallb.github.io/metallb
    releaseName: platform-metallb
    namespace: metallb-system
    valuesFile: values.yaml
