apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - namespace.yaml
components:
  - ../../components/network-isolation
  - ../../components/external-web-egress
  - ../../components/external-object-storage-egress
helmGlobals:
  chartHome: charts
helmCharts:
  - name: loki
    releaseName: loki
    namespace: logging
    valuesFile: values.yaml
  - name: alloy
    releaseName: alloy
    namespace: logging
    valuesFile: alloy-values.yaml
patches:
  - path: gateway-rke2-dns-patch.yaml
