apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: step-ca

helmCharts:
  - name: step-certificates
    repo: https://smallstep.github.io/helm-charts/
    releaseName: step-ca
    namespace: step-ca
    valuesFile: values.yaml
