apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmCharts:
  - name: argo-cd
    version: 10.0.0
    repo: https://argoproj.github.io/argo-helm
    releaseName: argo-cd
    namespace: argocd
    valuesFile: values.yaml
patches:
  - target:
      version: v1
      kind: Service
      name: argo-cd-argocd-repo-server
    patch: |-
      - op: add
        path: /spec/clusterIP
        value: "None"
      - op: add
        path: /spec/publishNotReadyAddresses
        value: false
  - target:
      version: v1
      kind: Service
      name: argo-cd-redis-ha-haproxy
    patch: |-
      - op: add
        path: /spec/clusterIP
        value: "None"
      - op: add
        path: /spec/publishNotReadyAddresses
        value: false
