configuration:
  features: EnableCSI
  defaultVolumesToFsBackup: false
  backupStorageLocation:
    - name: default
      provider: <BACKUP_PROVIDER>
      bucket: <BACKUP_BUCKET>
      config:
        region: <OBJECT_STORAGE_REGION>
        s3Url: <BACKUP_OBJECT_STORAGE_ENDPOINT>
        s3ForcePathStyle: "true"
  volumeSnapshotLocation:
    - name: default
      provider: <BACKUP_PROVIDER>
      config:
        region: <OBJECT_STORAGE_REGION>

credentials:
  useSecret: true
  existingSecret: velero-credentials

deployNodeAgent: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

nodeAgent:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      memory: 1Gi

snapshotsEnabled: true

schedules:
  platform-daily:
    disabled: false
    schedule: <VELERO_DAILY_BACKUP_CRON>
    template:
      ttl: 720h0m0s
      snapshotMoveData: true
      includedNamespaces:
        - argocd
        - cert-manager
        - cnpg-system
        - external-secrets
        - forgejo
        - harbor
        - keycloak
        - logging
        - longhorn-system
        - metallb-system
        - monitoring
        - object-storage
        - openbao
        - platform-cache
        - platform-databases
        - step-ca
        - tetragon
        - traefik
        - velero
        - woodpecker

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
