apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - namespace.yaml
  - crds/postgresql.cnpg.io_backups.yaml
  - crds/postgresql.cnpg.io_clusterimagecatalogs.yaml
  - crds/postgresql.cnpg.io_clusters.yaml
  - crds/postgresql.cnpg.io_databaseroles.yaml
  - crds/postgresql.cnpg.io_databases.yaml
  - crds/postgresql.cnpg.io_failoverquorums.yaml
  - crds/postgresql.cnpg.io_imagecatalogs.yaml
  - crds/postgresql.cnpg.io_poolers.yaml
  - crds/postgresql.cnpg.io_publications.yaml
  - crds/postgresql.cnpg.io_scheduledbackups.yaml
  - crds/postgresql.cnpg.io_subscriptions.yaml
helmGlobals:
  chartHome: charts
helmCharts:
  - name: cloudnative-pg
    releaseName: cloudnative-pg
    namespace: cnpg-system
    valuesFile: values.yaml
