apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: object-storage
components:
  - ../../components/network-isolation
  - ../../components/external-web-egress
  - ../../components/external-object-storage-egress
resources:
  - namespace.yaml
helmGlobals:
  chartHome: charts/minio-17.0.21
helmCharts:
  - name: minio
    releaseName: platform-minio
    namespace: object-storage
    valuesFile: values.yaml
patches:
  - path: image-compatibility-patch.yaml
