apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: object-storage
resources:
  - namespace.yaml
helmCharts:
  - name: minio
    version: 17.0.21
    repo: https://charts.bitnami.com/bitnami
    releaseName: platform-minio
    namespace: object-storage
    valuesFile: values.yaml
patches:
  - path: image-compatibility-patch.yaml
