apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
helmCharts:
  - name: forgejo
    version: 15.0.3
    repo: oci://code.forgejo.org/forgejo-helm
    releaseName: forgejo
    namespace: forgejo
    valuesFile: values.yaml
