apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
helmGlobals:
  chartHome: charts/forgejo-15.0.3
helmCharts:
  - name: forgejo
    releaseName: forgejo
    namespace: forgejo
    valuesFile: values.yaml
