apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-server
  namespace: openbao
spec:
  secretName: openbao-server-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - openbao
    - openbao.openbao
    - openbao.openbao.svc
    - openbao.openbao.svc.cluster.local
    - openbao-active
    - openbao-active.openbao
    - openbao-active.openbao.svc
    - openbao-active.openbao.svc.cluster.local
    - openbao-standby
    - openbao-standby.openbao
    - openbao-standby.openbao.svc
    - openbao-standby.openbao.svc.cluster.local
    - "*.openbao-internal"
    - "*.openbao-internal.openbao"
    - "*.openbao-internal.openbao.svc"
    - "*.openbao-internal.openbao.svc.cluster.local"
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: platform-internal-ca
    kind: ClusterIssuer
    group: cert-manager.io
