apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tetragon
resources:
  - namespace.yaml
helmCharts:
  - name: tetragon
    version: 1.6.0
    repo: https://helm.cilium.io
    releaseName: tetragon
    namespace: tetragon
    valuesFile: values.yaml
