apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-cache
resources:
  - namespace.yaml
  - service-primary.yaml
helmCharts:
  - name: valkey
    version: 0.10.0
    repo: https://valkey.io/valkey-helm
    releaseName: platform-valkey
    namespace: platform-cache
    valuesFile: values.yaml
