apiVersion: v1
kind: Service
metadata:
  name: platform-valkey-primary
  namespace: platform-cache
  labels:
    app.kubernetes.io/component: primary-proxy
    app.kubernetes.io/instance: platform-valkey
    app.kubernetes.io/name: valkey
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 6379
      protocol: TCP
      targetPort: primary-proxy
  selector:
    app.kubernetes.io/instance: platform-valkey
    app.kubernetes.io/name: valkey
