apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - namespace.yaml
  - storageclasses.yaml
  - filesystem-trim-recurring-job.yaml
helmGlobals:
  chartHome: charts/longhorn-1.12.1
helmCharts:
  - name: longhorn
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml
