persistence:
  defaultClass: false

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  backupTarget: "<LONGHORN_BACKUP_TARGET>"
  backupTargetCredentialSecret: <LONGHORN_BACKUP_CREDENTIAL_SECRET_NAME>
  createDefaultDiskLabeledNodes: false
  defaultReplicaCount: 2
  defaultDataLocality: best-effort
  replicaAutoBalance: best-effort
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 10
  orphanAutoDeletion: true
  concurrentAutomaticEngineUpgradePerNodeLimit: 1

longhornManager:
  priorityClass: longhorn-critical
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

longhornDriver:
  priorityClass: longhorn-critical
