persistence:
  defaultClass: false

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  backupTarget: "<LONGHORN_BACKUP_TARGET>"
  backupTargetCredentialSecret: <LONGHORN_BACKUP_CREDENTIAL_SECRET_NAME>
  createDefaultDiskLabeledNodes: false
  defaultReplicaCount: 2
  defaultDataLocality: best-effort
  replicaAutoBalance: best-effort
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 25
  orphanResourceAutoDeletion: "replica-data;instance"
  orphanResourceAutoDeletionGracePeriod: 300
  removeSnapshotsDuringFilesystemTrim: false
  autoCleanupSystemGeneratedSnapshot: true
  autoCleanupRecurringJobBackupSnapshot: true
  concurrentAutomaticEngineUpgradePerNodeLimit: 1

longhornManager:
  priorityClass: longhorn-critical
  tolerations:
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

longhornDriver:
  priorityClass: longhorn-critical
