profile: ingress-nginx
summary: Use ingress-nginx instead of the default Traefik ingress controller.
components:
  ingress: ingress-nginx
remove:
  - gitops/clusters/rke2-main/apps/traefik
include:
  - gitops/clusters/rke2-main/apps/ingress-nginx
