apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-databases
components:
  - ../../components/network-isolation
  - ../../components/external-web-egress
  - ../../components/external-object-storage-egress
  - ../../components/kubernetes-api-egress
resources:
  - namespace.yaml
  - allow-postgres-ingress.yaml
  - postgres-cluster.yaml
  - keycloak-database.yaml
  - woodpecker-database.yaml
  - harbor-database.yaml
  - grafana-database.yaml
