apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-databases
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - keycloak-database.yaml
  - woodpecker-database.yaml
  - harbor-database.yaml
  - grafana-database.yaml
