apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - namespace.yaml
components:
  - ../../components/network-isolation
  - ../../components/postgres-client
  - ../../components/valkey-client
  - ../../components/external-web-egress
  - ../../components/external-smtp-egress
  - ../../components/external-database-egress
  - ../../components/external-object-storage-egress
helmGlobals:
  chartHome: charts/harbor-1.19.1
helmCharts:
  - name: harbor
    releaseName: harbor
    namespace: harbor
    valuesFile: values.yaml
patches:
  - path: jobservice-redis-config-patch.yaml
  - path: ca-bundle-configmap-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: harbor-(core|exporter|jobservice|registry)
  - path: ca-bundle-configmap-statefulset-patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: harbor-trivy
