apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - kubelet-health-policy.yaml
helmCharts:
  - name: argo-cd
    version: 10.0.0
    repo: https://argoproj.github.io/argo-helm
    releaseName: argo-cd
    namespace: argocd
    valuesFile: values.yaml
