# Argo CD HA profile.

server:
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - argocd.<PLATFORM_DOMAIN>

repoServer:
  replicas: 2

applicationSet:
  replicas: 2

redis-ha:
  enabled: true

configs:
  params:
    server.insecure: true
