FROM eclipse-temurin:21-jdk-alpine@sha256:1ff763083f2993d57d0bf374ab10bb3e2cb873af6c13a04458ebbd3e0337dc76
WORKDIR /app
COPY . /app
CMD ["sh", "-lc", "echo \"compile with kotlinc in your final image\""]
