apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - namespace.yaml
components:
  - ../../components/network-isolation
  - ../../components/postgres-client
  - ../../components/valkey-client
  - ../../components/external-web-egress
  - ../../components/external-git-egress
  - ../../components/external-smtp-egress
  - ../../components/external-database-egress
  - ../../components/external-object-storage-egress
helmGlobals:
  chartHome: charts/forgejo-17.1.4
helmCharts:
  - name: forgejo
    releaseName: forgejo
    namespace: forgejo
    valuesFile: values.yaml
