apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - namespace.yaml
components:
  - ../../components/network-isolation
  - ../../components/postgres-client
  - ../../components/valkey-client
  - ../../components/external-web-egress
  - ../../components/external-git-egress
  - ../../components/external-smtp-egress
  - ../../components/external-database-egress
helmCharts:
  - name: forgejo
    version: 15.0.3
    repo: oci://code.forgejo.org/forgejo-helm
    releaseName: forgejo
    namespace: forgejo
    valuesFile: values.yaml
